default_stages: [commit]
repos:
  # >>>>>>>>>>>>>>>>>>>>> basic <<<<<<<<<<<<<<<<<<<< #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      # - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.4'
    hooks:
      - id: prettier
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v2.40.0'
    hooks:
      - id: commitizen
        stages: [commit-msg]
  # >>>>>>>>>>>>>>>>>>>>> basic <<<<<<<<<<<<<<<<<<<< #

  # >>>>>>>>>>>>>>>>>>>>> bash <<<<<<<<<<<<<<<<<<<< #
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 'v3.6.0-1'
    hooks:
      - id: shfmt
        args: ['-w', '-i', '2', '-s', '-l', '-ci']
  # >>>>>>>>>>>>>>>>>>>>> bash <<<<<<<<<<<<<<<<<<<< #

  # >>>>>>>>>>>>>>>>>>>>> python <<<<<<<<<<<<<<<<<<<< #
  - repo: https://github.com/google/yapf
    rev: 'v0.32.0'
    hooks:
      - id: yapf
        additional_dependencies: [toml]
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.3.1'
    hooks:
      - id: pyupgrade
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ['--line-length=100']
  # >>>>>>>>>>>>>>>>>>>>> python <<<<<<<<<<<<<<<<<<<< #

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: 'v0.6.13'
    hooks:
      - id: cmake-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v15.0.7'
    hooks:
      - id: clang-format
        'types_or': [c++, c, c#, cuda, java, objective-c, proto]
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: '6.0.0'
    hooks:
      - id: buildifier
