name: 'Setup cuda'
description: 'setup cuda'
inputs:
  cuda_version:
    equired: false
    default: '12.5'
  enable_cudnn:
    required: false
    default: 'false'
  cudnn_version:
    required: false
    default: '8'

runs:
  using: 'composite'
  steps:
    - name: cache cuda
      id: cache-cuda
      uses: actions/cache@v4
      with:
        path: cuda_pkg
        key: ${{ inputs.cuda_version }}

    - name: cache cudnn
      id: cache-cudnn
      if: inputs.enable_cudnn == 'true'
      uses: actions/cache@v4
      with:
        path: cudnn_pkg
        key: ${{ inputs.cudnn_version }}

    - name: download cuda
      if: steps.cache-cuda.outputs.cache-hit != 'true'
      shell: bash
      run: |
        if [[ ${{ inputs.cuda_version }} == '12.5' ]]; then
          mkdir -p cuda_pkg
          curl -sSL -o cuda_pkg/cuda.deb https://developer.download.nvidia.com/compute/cuda/12.5.0/local_installers/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb
        fi

    - name: install cuda
      shell: bash
      run: |
        curl -sSL -o cuda-ubuntu2204.pin https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
        sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo dpkg -i cuda_pkg/cuda.deb
        sudo cp /var/cuda-repo-ubuntu2204-12-5-local/cuda-*-keyring.gpg /usr/share/keyrings/
        sudo apt-get update -y
        sudo apt-get -y install cuda-toolkit-12-5

    - name: download cudnn
      if: inputs.enable_cudnn == 'true' && steps.cache-cudnn.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p cudnn_pkg
        if [[ ${{ inputs.cudnn_version }} == '8' ]]; then
          curl -sSL -o cudnn_pkg/cudnn.deb https://developer.download.nvidia.com/compute/redist/cudnn/v8.8.0/local_installers/12.0/cudnn-local-repo-ubuntu2204-8.8.0.121_1.0-1_amd64.deb
        elif [[ ${{ inputs.cudnn_version }} == '9' ]]; then
          curl -sSL -o cudnn_pkg/cudnn.deb https://developer.download.nvidia.com/compute/cudnn/9.1.1/local_installers/cudnn-local-repo-ubuntu2204-9.1.1_1.0-1_amd64.deb
        fi

    - name: install cudnn
      if: inputs.enable_cudnn == 'true'
      shell: bash
      run: |
        if [[ ${{ inputs.enable_cudnn }} == 'true' ]]; then
          if [[ ${{ inputs.cudnn_version }} == '8' ]]; then
            sudo dpkg -i cudnn_pkg/cudnn.deb
            sudo cp /var/cudnn-local-repo-ubuntu2204-8.8.0.121/cudnn-*-keyring.gpg /usr/share/keyrings/
            sudo apt-get update -y
            sudo apt-get -y install libcudnn8-dev
          elif [[ ${{ inputs.cudnn_version }} == '9' ]]; then
            sudo dpkg -i cudnn_pkg/cudnn.deb
            sudo cp /var/cudnn-local-repo-ubuntu2204-9.1.1/cudnn-*-keyring.gpg /usr/share/keyrings/
            sudo apt-get update -y
            sudo apt-get -y install cudnn
            sudo apt-get -y install cudnn-cuda-12
          fi
        fi
