name: 'Setup cuda'
description: 'setup cuda'
inputs:
  cuda_version:
    equired: false
    default: '12.5'
  enable_cudnn:
    required: false
    default: 'false'
  cudnn_version:
    required: false
    default: '8'

outputs:

runs:
  using: 'composite'
  steps:
    - name: setup cuda
      shell: bash
      run: |
        if [[ ${{ inputs.cuda_version }} == '12.5' ]]; then
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
          sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
          wget https://developer.download.nvidia.com/compute/cuda/12.5.0/local_installers/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb
          sudo dpkg -i cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb
          sudo cp /var/cuda-repo-ubuntu2204-12-5-local/cuda-*-keyring.gpg /usr/share/keyrings/
          sudo apt-get update -y
          sudo apt-get -y install cuda-toolkit-12-5
          rm -rf cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb
        fi

        if [[ ${{ inputs.enable_cudnn }} == 'true' ]]; then
          if [[ ${{ inputs.cudnn_version }} == '8' ]]; then
            wget https://developer.download.nvidia.com/compute/redist/cudnn/v8.8.0/local_installers/12.0/cudnn-local-repo-ubuntu2204-8.8.0.121_1.0-1_amd64.deb
            sudo dpkg -i cudnn-local-repo-ubuntu2204-8.8.0.121_1.0-1_amd64.deb
            sudo cp /var/cudnn-local-repo-ubuntu2204-8.8.0.121/cudnn-*-keyring.gpg /usr/share/keyrings/
            sudo apt-get update
            sudo apt-get -y install libcudnn8-dev
            rm -rf cudnn-local-repo-ubuntu2204-8.8.0.121_1.0-1_amd64.deb
          elif [[ ${{ inputs.cudnn_version }} == '9' ]]; then
            wget https://developer.download.nvidia.com/compute/cudnn/9.1.1/local_installers/cudnn-local-repo-ubuntu2204-9.1.1_1.0-1_amd64.deb
            sudo dpkg -i cudnn-local-repo-ubuntu2204-9.1.1_1.0-1_amd64.deb
            sudo cp /var/cudnn-local-repo-ubuntu2204-9.1.1/cudnn-*-keyring.gpg /usr/share/keyrings/
            sudo apt-get update
            sudo apt-get -y install cudnn
            sudo apt-get -y install cudnn-cuda-12
            rm -rf cudnn-local-repo-ubuntu2204-9.1.1_1.0-1_amd64.deb
          fi
        fi
