name: cuda

on:
  push:
    paths:
      - .github/workflows/cuda-docker.yaml
      - cuda/docker/**
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version:
          - cu11.4-cudnn8
          - cu12.3-cudnn8
          - cu12.3-cudnn9

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: curoky
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: cuda/docker
          file: cuda/docker/${{ matrix.version }}.Dockerfile
          push: true
          tags: curoky/infra-image:${{ matrix.version }}
          cache-from: type=registry,ref=curoky/infra-image:__cache_${{ matrix.version }}
          cache-to: type=inline
