name: cuda

on:
  push:
    paths:
      - .github/workflows/cuda.yaml
      - cuda/**
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build-with-bazel:
    defaults:
      run:
        working-directory: cuda/build-with-bazel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: ./github-actions/setup-cuda
        with:
          cuda_version: '12.5'
          enable_cudnn: 'true'
          cudnn_version: '8'

      - run: bazel build :main

  build-with-bazel-bzlmod:
    defaults:
      run:
        working-directory: cuda/build-with-bazel-bzlmod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: ./github-actions/setup-cuda
        with:
          cuda_version: '12.5'
          enable_cudnn: 'true'
          cudnn_version: '8'

      - run: bazel build :main

  build-with-nvcc:
    defaults:
      run:
        working-directory: cuda/build-with-nvcc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: ./github-actions/setup-cuda
        with:
          cuda_version: '12.5'
          enable_cudnn: 'true'
          cudnn_version: '8'

      - run: /usr/local/cuda/bin/nvcc -lcudart_static -o main main.cu
