name: gh cleanup disk

on:
  push:
    paths:
      - .github/workflows/gh-cleanup-disk.yaml
  workflow_dispatch:

jobs:
  show_disk_usage_ubuntu_22_04:
    runs-on: ubuntu-latest
    steps:
      - name: run ncdu
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ncdu
          ncdu -o disk_usage.data -q --color off /

      - uses: actions/upload-artifact@v4
        with:
          name: disk_usage.data
          path: disk_usage.data

      - run: df -h
      - run: du -ahd2 2>&1 | sort -h | grep --color -v "Permission denied"

  cleanup_method1:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main

      - run: df -h
      - run: du -ahd2 2>&1 | sort -h | grep --color -v "Permission denied"

  cleanup_method2:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - run: df -h
      - run: du -ahd2 2>&1 | sort -h | grep --color -v "Permission denied"

  cleanup_method3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: github-actions/cleanup-disk/free-github-action-disk-space.sh

      - run: df -h
      - run: du -ahd2 2>&1 | sort -h | grep --color -v "Permission denied"
