name: maven

on:
  push:
    paths:
      - .github/workflows/maven.yaml
      - maven/**
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'

      # @deprecated
      - uses: actions/cache@v3
        if: 'false'
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # - name: Setup Maven
      #   uses: stCarolas/setup-maven@v4.3
      #   with:
      #     maven-version: 3.8.5

      - name: Build
        run: mvn -B compile -e --file pom.xml
        working-directory: maven/hello
