name: pipy publish via poetry

on:
  push:
    paths:
      - .github/workflows/pypi-publish-via-poetry.yaml
      - python/poetry/**
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: python/poetry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install poetry

      # - uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cache/pypoetry
      #       .venv
      #     key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - run: 'sed -i "s/1.0.0/$(date +%Y.%-m.%d).post1.dev$(date +%s)/g" pyproject.toml'

      - run: poetry install

      - run: poetry run pytest . || echo ignore error

      - run: poetry build

      - name: Publish a Python distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: python/poetry/dist
