name: tensorflow usage

on:
  push:
    paths:
      - .github/workflows/tensorflow-usage.yaml
      - tensorflow/usage/**
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  tf_2_5_gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./github-actions/setup-cuda
        with:
          cuda_version: '11.4'
          enable_cudnn: 'true'
          cudnn_version: '8'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install protobuf==3.20.* tensorflow==2.5.0

      - run: ./build.sh
        working-directory: tensorflow/usage/build-with-pip-prebuilt/tf2_5_gcc

  tf_2_16_gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./github-actions/setup-cuda
        with:
          cuda_version: '12.3'
          enable_cudnn: 'true'
          cudnn_version: '8'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install protobuf==4.25.3 tensorflow==2.16.1

      - run: ./build.sh
        working-directory: tensorflow/usage/build-with-pip-prebuilt/tf2_16_gcc

  tf_2_5_bazel:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - uses: ./github-actions/setup-cuda
        with:
          cuda_version: '11.4'
          enable_cudnn: 'true'
          cudnn_version: '8'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install protobuf==3.20.* tensorflow==2.5.0

      - run: sed -i -e "s#/app/conda/envs/tf2.5/lib/python3.8/site-packages#$(pip list -v | grep 'tensorflow ' | grep -o -E '[^ ]*site[^ ]*')#g" WORKSPACE
        working-directory: tensorflow/usage/build-with-pip-prebuilt/tf2_5_bazel

      - run: bazel build :add_one
        working-directory: tensorflow/usage/build-with-pip-prebuilt/tf2_5_bazel

  tf_2_16_bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - uses: ./github-actions/setup-cuda
        with:
          cuda_version: '12.3'
          enable_cudnn: 'true'
          cudnn_version: '8'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install protobuf==4.25.3 tensorflow==2.16.1

      - run: sed -i -e "s#/app/conda/envs/tf2.16/lib/python3.11/site-packages#$(pip list -v | grep 'tensorflow ' | grep -o -E '[^ ]*site[^ ]*')#g" WORKSPACE
        working-directory: tensorflow/usage/build-with-pip-prebuilt/tf2_16_bazel

      - run: bazel build :add_one
        working-directory: tensorflow/usage/build-with-pip-prebuilt/tf2_16_bazel
